# Generated by Django 2.2 on 2019-05-01 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dzielnica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Dzielnice',
            },
        ),
        migrations.CreateModel(
            name='Gmina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Gminy',
            },
        ),
        migrations.CreateModel(
            name='Konkurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_finish', models.DateTimeField()),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name_plural': 'Konkursy',
            },
        ),
        migrations.CreateModel(
            name='Projekt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('rl_from', models.DateTimeField()),
                ('rl_to', models.DateTimeField()),
                ('name', models.CharField(max_length=22)),
                ('project_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('project_funds', models.DecimalField(decimal_places=2, max_digits=6)),
                ('attachment', models.FileField(upload_to='attachments/projects')),
                ('dzielnica_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekty_gminne.Dzielnica')),
                ('konkurs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekty_gminne.Konkurs')),
            ],
            options={
                'verbose_name_plural': 'Projekty',
            },
        ),
        migrations.CreateModel(
            name='Glos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=11)),
                ('projekt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekty_gminne.Projekt')),
            ],
            options={
                'verbose_name_plural': 'Głosy',
            },
        ),
        migrations.AddField(
            model_name='dzielnica',
            name='projekt_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekty_gminne.Gmina'),
        ),
        migrations.CreateModel(
            name='ApiMockData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('pesel', models.DecimalField(decimal_places=0, max_digits=11)),
                ('dzielnica_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekty_gminne.Dzielnica')),
            ],
            options={
                'verbose_name_plural': 'ApiMockData',
            },
        ),
    ]
