# Generated by Django 2.2 on 2019-05-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekty_gminne', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apimockdata',
            name='pesel',
            field=models.CharField(max_length=11),
        ),
    ]
