# Generated by Django 2.2 on 2019-05-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekty_gminne', '0004_auto_20190502_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='projekt',
            name='wnioskodawca',
            field=models.CharField(default='default', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projekt',
            name='instytucja_wdrazajaca',
            field=models.CharField(max_length=256),
        ),
    ]
