# Generated by Django 2.2 on 2019-05-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekty_gminne', '0005_auto_20190502_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projekt',
            name='project_funds',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='projekt',
            name='project_value',
            field=models.CharField(max_length=32),
        ),
    ]
