# Generated by Django 2.2 on 2019-05-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekty_gminne', '0006_auto_20190502_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projekt',
            old_name='project_funds',
            new_name='kwota_dofinansowania',
        ),
        migrations.RenameField(
            model_name='projekt',
            old_name='project_value',
            new_name='wartosc_projektu',
        ),
        migrations.AddField(
            model_name='projekt',
            name='waluta',
            field=models.CharField(choices=[('PLN', 'PLN'), ('USD', 'USD'), ('EUR', 'EUR')], default='PLN', max_length=3),
        ),
        migrations.AlterField(
            model_name='projekt',
            name='okres_realizacji_do',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='projekt',
            name='okres_realizacji_od',
            field=models.DateField(),
        ),
    ]
