# Generated by Django 2.2 on 2019-05-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekty_gminne', '0007_auto_20190502_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='projekt',
            name='widocznosc',
            field=models.BooleanField(default=False),
        ),
    ]
