# Generated by Django 2.2 on 2019-05-03 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projekty_gminne', '0008_projekt_widocznosc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projekt',
            name='konkurs_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projekty_gminne.Konkurs'),
        ),
    ]
